---
- name: Install libselinux-python
  yum: name=libselinux-python
  become: True
  become_method: sudo
  when: "ansible_os_family == 'RedHat'"
  
- name: Install java
  yum: name=java-1.8.0-openjdk
  become: True
  become_method: sudo
  when: "ansible_os_family == 'RedHat'"

- name: Install pip
  yum: name=python2-pip
  become: True
  become_method: sudo
  when: "ansible_os_family == 'RedHat'"

- name: Install es-py lib
  pip: name=elasticsearch
  become: True
  become_method: sudo
  when: "ansible_os_family == 'RedHat'"